name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.17.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: apk add --no-cache gcc libc-dev
    - name: Test Frontend
      run: cd frontend && go test
    - name: Test Backend
      run: cd ../backend && go test
