name: CI

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.17.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: apk add --no-cache gcc libc-dev
    - name: Test Frontend
      run: cd frontend && go test
  Build-Push-Frontend:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ahmadhamid/cookie-frontend:latest

  Build-Push-Backend:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ahmadhamid/cookie-backend:latest