name: CI

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test:
    runs-on: [self-hosted]
    container: golang:1.17.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: apk add --no-cache gcc libc-dev
    - name: Test Frontend
      run: cd frontend && go test
  Build-Push:
    runs-on: [self-hosted]
    needs: [Test]
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ahmadhamid/cookie-frontend:${{ GITHUB_REF }}
    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ahmadhamid/cookie-backend:${{ GITHUB_REF }}
  Deploy:
    runs-on: [self-hosted]
    needs: [Build-Push]
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker-Compose
      run: docker-compose up -d